[tox]
requires = tox>=4
envlist = ruff,black,bandit

[testenv]
package = skip
use_current_env = true

[testenv:ruff]
commands = ruff check {posargs:lfs_shimmy}
allowlist_externals = ruff

[testenv:black]
commands = black --check {posargs:lfs_shimmy}
allowlist_externals = black

[testenv:bandit]
commands = bandit -r {posargs:lfs_shimmy}
allowlist_externals = bandit
