name: CI
on: { pull_request: { } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  setup-build:
    uses: infrabits/ci-setup-tox-env/.github/workflows/setup.yml@541da38f95bc05d926ce24f5c5bcf3951907dabd # main

  execute-lint:
    needs: [setup-build]
    uses: infrabits/ci-run-tox-env/.github/workflows/run.yml@19f9bbd03df394ba63d7644e7afa80dcf6adfb2a # main
    with:
      environments: ${{ needs.setup-build.outputs.lint }}

  execute-test:
    needs: [setup-build]
    uses: infrabits/ci-run-tox-env/.github/workflows/run.yml@19f9bbd03df394ba63d7644e7afa80dcf6adfb2a # main
    with:
      environments: ${{ needs.setup-build.outputs.test }}
      install_dependencies: true

  build-container:
    runs-on: ubuntu-latest
    needs: [setup-build, execute-lint, execute-test]
    permissions:
      security-events: write
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Build container
        uses: infrabits/ci-pack@c72247fc9ba1598090115c1d099e5c779b8bc79c # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          use_builder: upstream
          publish_image: false
