name: Create Release For Renovate
on: { push: { branches: [ 'main' ] } }
jobs:
  renovate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: infrabits/ci-create-renovate-release@fc576bc9707b246ea12f466a6e18b742815d73a7 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
