name: Create Release For Renovate
on: { push: { branches: [ 'main' ] } }
jobs:
  renovate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: infrabits/ci-create-renovate-release@5a258b2f38abb45f3c87d25fb68f37ca72d932aa # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
